name: Ejecutar pruebas CodeceptJS

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codecept-test:
    runs-on: ubuntu-latest

    steps:
      - name: Hacer checkout del repo
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm ci

      - name: Instalar dependencias del sistema
        run: sudo apt-get install -y xvfb libxss1 libappindicator3-1 libasound2

      - name: Instalar navegadores de Playwright
        run: npx playwright install

      - name: Ejecutar pruebas con Xvfb
        run: xvfb-run -a npx codeceptjs run --verbose

   